# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-09-22 12:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='card',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 9, 22, 12, 3, 55, 608394, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
